name: Build and publish wheels

on:
  push:
    tags:
      - 'v*'
  pull_request:
    paths:
      - '.github/workflows/build-wheels.yml'
  workflow_dispatch:

jobs:
  build_wheels_linux:
    name: Build Linux wheels
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    strategy:
      matrix:
        python-version: ['cp38-cp38', 'cp39-cp39', 'cp310-cp310', 'cp311-cp311', 'cp312-cp312']

    steps:
    - uses: actions/checkout@v4

    - name: Build wheel
      run: |
        /opt/python/${{ matrix.python-version }}/bin/pip install setuptools wheel pybind11 numpy
        /opt/python/${{ matrix.python-version }}/bin/python setup.py bdist_wheel
        auditwheel repair dist/*.whl -w dist/
        rm dist/*-linux_*.whl

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-linux-${{ matrix.python-version }}
        path: ./dist/*.whl

  build_wheels_other:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel pybind11 numpy

    - name: Build wheel
      run: |
        python setup.py bdist_wheel

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.os }}-py${{ matrix.python-version }}
        path: ./dist/*.whl

  publish:
    name: Publish to PyPI
    needs: [build_wheels_linux, build_wheels_other]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - uses: actions/download-artifact@v4
      with:
        path: dist

    - name: Flatten dist directory
      run: |
        mkdir -p flat_dist
        find dist -name "*.whl" -exec mv {} flat_dist/ \;
        rm -rf dist
        mv flat_dist dist

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
